### ISSUE TITLE
mongo-c-driver/src/bson.c:632: error: comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by zhangrt** [barakethan/gridfs-nginx-plugin#1]
how to fix it

**Comment by barakethan** [comment]
very simple the compiler will show you there are the line numbers of the error.
go to this lines and add (unsigned long) in the places there is a comparison issue to the int side. (if ( pos + bytesNeeded <= (unsigned long) b->dataSize ))

I had the same thing and after adding this it compiled correctly.

**Comment by zhangrt** [comment]
ok, thanks
